namespace: 

replicaCount: 1

image:
  repository: d0bl3c3r0/low-code-engine
  tag: latest
  pullPolicy: IfNotPresent

service:
  enabled: true
  type: NodePort

env:
  NODE_ENV: development
  TIME_ZONE: America/Fortaleza
  SERVER_ACTIVE: true
  SERVER_PORT: 3000
  SERVER_BODY_LIMIT: 500kb
  DB_HOST: kubernetes.docker.internal
  DB_PORT: 3306
  DB_USERNAME: root
  DB_DATABASE: low-code-engine
  DB_DEBUG: false
  REDIS_HOST: localhost
  REDIS_PORT: 6379
  REDIS_PREFIX: low-code-engine
  APM_SERVER_URL: http://kubernetes.docker.internal:8200
  APM_SERVICE_NAME: low-code-engine
  APM_API_KEY: 
  APM_SECRET_TOKEN: 

secret:
  DB_PASSWORD: admin

resources:
  requests:
    memory: "128Mi"
    cpu: 100m
  limits:
    memory: "500Mi"
    cpu: 200m

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 60
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 60