apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: low-code-engine-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: clow-code-engine
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50