apiVersion: v1
kind: Service
metadata:
  name: low-code-engine
spec:
  selector:
    app: low-code-engine
  ports:
  - port: 3000
    nodePort: 31000
    targetPort: low-code-engine-port
    protocol: TCP
  type: NodePort